# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: worker.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'worker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cworker.proto\x12\x06worker\"-\n\nJobRequest\x12\x0e\n\x06rfp_id\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\t\"/\n\x0bJobResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2F\n\rWorkerService\x12\x35\n\nEnqueueJob\x12\x12.worker.JobRequest\x1a\x13.worker.JobResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'worker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JOBREQUEST']._serialized_start=24
  _globals['_JOBREQUEST']._serialized_end=69
  _globals['_JOBRESPONSE']._serialized_start=71
  _globals['_JOBRESPONSE']._serialized_end=118
  _globals['_WORKERSERVICE']._serialized_start=120
  _globals['_WORKERSERVICE']._serialized_end=190
# @@protoc_insertion_point(module_scope)
