# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rag.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'rag.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trag.proto\x12\x03rag\"5\n\rIngestRequest\x12\x13\n\x0b\x64ocument_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\" \n\x0eIngestResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x1d\n\x0cQueryRequest\x12\r\n\x05query\x18\x01 \x01(\t\"9\n\rQueryResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\x12\x18\n\x10source_documents\x18\x02 \x01(\t2o\n\nRagService\x12\x31\n\x06Ingest\x12\x12.rag.IngestRequest\x1a\x13.rag.IngestResponse\x12.\n\x05Query\x12\x11.rag.QueryRequest\x1a\x12.rag.QueryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rag_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INGESTREQUEST']._serialized_start=18
  _globals['_INGESTREQUEST']._serialized_end=71
  _globals['_INGESTRESPONSE']._serialized_start=73
  _globals['_INGESTRESPONSE']._serialized_end=105
  _globals['_QUERYREQUEST']._serialized_start=107
  _globals['_QUERYREQUEST']._serialized_end=136
  _globals['_QUERYRESPONSE']._serialized_start=138
  _globals['_QUERYRESPONSE']._serialized_end=195
  _globals['_RAGSERVICE']._serialized_start=197
  _globals['_RAGSERVICE']._serialized_end=308
# @@protoc_insertion_point(module_scope)
