# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import gap_engine_pb2 as gap__engine__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in gap_engine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GapEngineServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeGaps = channel.unary_unary(
                '/gap_engine.GapEngineService/AnalyzeGaps',
                request_serializer=gap__engine__pb2.GapRequest.SerializeToString,
                response_deserializer=gap__engine__pb2.GapResponse.FromString,
                _registered_method=True)


class GapEngineServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AnalyzeGaps(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GapEngineServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeGaps': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeGaps,
                    request_deserializer=gap__engine__pb2.GapRequest.FromString,
                    response_serializer=gap__engine__pb2.GapResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gap_engine.GapEngineService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gap_engine.GapEngineService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GapEngineService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AnalyzeGaps(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gap_engine.GapEngineService/AnalyzeGaps',
            gap__engine__pb2.GapRequest.SerializeToString,
            gap__engine__pb2.GapResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
