# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gap_engine.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'gap_engine.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10gap_engine.proto\x12\ngap_engine\"\x1c\n\nGapRequest\x12\x0e\n\x06rfp_id\x18\x01 \x01(\t\"(\n\x03Gap\x12\x0c\n\x04\x61rea\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"<\n\x0bGapResponse\x12\x0e\n\x06rfp_id\x18\x01 \x01(\t\x12\x1d\n\x04gaps\x18\x02 \x03(\x0b\x32\x0f.gap_engine.Gap2R\n\x10GapEngineService\x12>\n\x0b\x41nalyzeGaps\x12\x16.gap_engine.GapRequest\x1a\x17.gap_engine.GapResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gap_engine_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GAPREQUEST']._serialized_start=32
  _globals['_GAPREQUEST']._serialized_end=60
  _globals['_GAP']._serialized_start=62
  _globals['_GAP']._serialized_end=102
  _globals['_GAPRESPONSE']._serialized_start=104
  _globals['_GAPRESPONSE']._serialized_end=164
  _globals['_GAPENGINESERVICE']._serialized_start=166
  _globals['_GAPENGINESERVICE']._serialized_end=248
# @@protoc_insertion_point(module_scope)
