# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import hunter_pb2 as proto_dot_hunter__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/hunter_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HunterServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Detect = channel.unary_stream(
                '/hunter.HunterService/Detect',
                request_serializer=proto_dot_hunter__pb2.DetectRequest.SerializeToString,
                response_deserializer=proto_dot_hunter__pb2.DetectResponse.FromString,
                _registered_method=True)
        self.Hunt = channel.unary_stream(
                '/hunter.HunterService/Hunt',
                request_serializer=proto_dot_hunter__pb2.HuntRequest.SerializeToString,
                response_deserializer=proto_dot_hunter__pb2.HuntResponse.FromString,
                _registered_method=True)


class HunterServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Detect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Hunt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HunterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Detect': grpc.unary_stream_rpc_method_handler(
                    servicer.Detect,
                    request_deserializer=proto_dot_hunter__pb2.DetectRequest.FromString,
                    response_serializer=proto_dot_hunter__pb2.DetectResponse.SerializeToString,
            ),
            'Hunt': grpc.unary_stream_rpc_method_handler(
                    servicer.Hunt,
                    request_deserializer=proto_dot_hunter__pb2.HuntRequest.FromString,
                    response_serializer=proto_dot_hunter__pb2.HuntResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hunter.HunterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hunter.HunterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HunterService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Detect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hunter.HunterService/Detect',
            proto_dot_hunter__pb2.DetectRequest.SerializeToString,
            proto_dot_hunter__pb2.DetectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Hunt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hunter.HunterService/Hunt',
            proto_dot_hunter__pb2.HuntRequest.SerializeToString,
            proto_dot_hunter__pb2.HuntResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
