# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hunter.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'hunter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0chunter.proto\x12\x06hunter\"\x1c\n\rDetectRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\"`\n\x0e\x44\x65tectResponse\x12\r\n\x05\x65vent\x18\x01 \x01(\t\x12\x14\n\x0cjson_payload\x18\x02 \x01(\t\x12)\n\x0cpayload_type\x18\x03 \x01(\x0e\x32\x13.hunter.PayloadType\":\n\x0bHuntRequest\x12\x11\n\tportal_id\x18\x01 \x01(\t\x12\x18\n\x10mock_config_json\x18\x02 \x01(\t\"^\n\x0cHuntResponse\x12\r\n\x05\x65vent\x18\x01 \x01(\t\x12\x14\n\x0cjson_payload\x18\x02 \x01(\t\x12)\n\x0cpayload_type\x18\x03 \x01(\x0e\x32\x13.hunter.PayloadType*!\n\x0bPayloadType\x12\x08\n\x04JSON\x10\x00\x12\x08\n\x04TEXT\x10\x01\x32\x7f\n\rHunterService\x12\x39\n\x06\x44\x65tect\x12\x15.hunter.DetectRequest\x1a\x16.hunter.DetectResponse0\x01\x12\x33\n\x04Hunt\x12\x13.hunter.HuntRequest\x1a\x14.hunter.HuntResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hunter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PAYLOADTYPE']._serialized_start=308
  _globals['_PAYLOADTYPE']._serialized_end=341
  _globals['_DETECTREQUEST']._serialized_start=24
  _globals['_DETECTREQUEST']._serialized_end=52
  _globals['_DETECTRESPONSE']._serialized_start=54
  _globals['_DETECTRESPONSE']._serialized_end=150
  _globals['_HUNTREQUEST']._serialized_start=152
  _globals['_HUNTREQUEST']._serialized_end=210
  _globals['_HUNTRESPONSE']._serialized_start=212
  _globals['_HUNTRESPONSE']._serialized_end=306
  _globals['_HUNTERSERVICE']._serialized_start=343
  _globals['_HUNTERSERVICE']._serialized_end=470
# @@protoc_insertion_point(module_scope)
